### ISSUE TITLE
Radar Data Format

### ISSUE THREAD

**Issue by LucasSloan** [commaai/comma2k19#14]
In the README, the radar data is described as having 6 components:

```
|  +--radar: [forward distance (m),
|  |          left distance (m),
|  |          nan,
|  |          nan,
|  |          address,
|  |          new_track (bool)]
```

However, when I dumped the numpy array it had a shape of (6770, 7).

Example data:

[ 50.9   -4.4    1.55    nan    nan 530.     0.  ]

Is it meant to be [forward distance, left distance, down distance, nan, nan, address, new track]?

**Comment by HaraldSchafer** [comment]
Oh sorry, I think the format is:
[forward distance, left distance, relative velocity (m/s), nan, nan, address, new track]

Must have overlooked that!

**Comment by LucasSloan** [comment]
Got it - thanks!
