### ISSUE TITLE
How to match video frame to `steering_angle` value

### ISSUE THREAD

**Issue by AshleyRudland** [commaai/comma2k19#15]
Probably being very dumb here, but I'm trying to map the `steering_angle` value to a frame in the video to try to build a very basic NN to input video frame and output steering_angle.

In your dataset example, the video contains 1200 frames, but the values from `processed_log/CAN/steering_angle/value` contains `4974` values.

The times in `processed_log/CAN/steering_angle/t` do not directly map to the times in `global_pose/frame_times`, how does one map a frame in the video to the values?

Thanks in advance!!

**Comment by AshleyRudland** [comment]
@BraunPhilipp @HaraldSchafer 😄

**Comment by BraunPhilipp** [comment]
Data was likely recorded via CAN or message daemons that have their own timestamps. To sync you will have to do a nearest neighbor search. The following will probably work for you.

```
example_segment = '../Example_1/b0c9d2329ad1606b|2018-08-02--08-34-47/40/'
can_time = np.load(example_segment + 'processed_log/CAN/radar/t')
fr_time = np.load(example_segment + 'global_pose/frame_times')

out = [min(range(len(can_time)), key=lambda can_idx: abs(can_time[can_idx]-ts)) for ts in fr_time]
```

**Comment by likui01** [comment]
@BraunPhilipp  @HaraldSchafer 
what is the unit of steering angle and how to normalize it. some values are really big, what do those values mean?
