### ISSUE TITLE
Where to obtain global orientations as quaternion from any OpenPilot log

### ISSUE THREAD

**Issue by davidtena98** [commaai/comma2k19#18]
Hi there.

Just wondering the procedure to calculate the quaternion from any OpenPilot log. I've seen that none of the messages sent in liveLocationKalman has 4 values. All of them are 3. So, how can I do it ?

many thanks in advance.

**Comment by HaraldSchafer** [comment]
Those are euler angles : roll, pitch yaw. You can convert them to quaternions.
