### ISSUE TITLE
Decoding/accessing raw_CAN signals

### ISSUE THREAD

**Issue by jdacoello** [commaai/comma2k19#19]
The dataset provides the decoded can data `radar`, `steering_wheel`, `speed`, and `wheel_speed`. However, it is unclear how can one access other signals that might be available within the raw can data at the path `segment_number/processed_log/CAN/raw_can/`.

In other words, is there a list of all the signals available in the `can_raw`, or how can you obtain it?

For example, how can I obtain the signals of the `blinking indicator light`, `pedal positions`, `gear number`, etc?

**Comment by HaraldSchafer** [comment]
https://github.com/commaai/opendbc

**Comment by jdacoello** [comment]
I am revisiting this issue after some time. 

I was not able to decode the data of the path `segment_number/processed_log/CAN/raw_can/`.
Could you please provide me some guidance. 
I see that the folder has 4 arrays (`t`,`src`,`address`,`data`).
<img width="447" alt="image" src="https://user-images.githubusercontent.com/8550265/161343872-00204f46-8b41-4c7f-9021-d8971db8d511.png">

This is not the direct CAN messages but rather a preprocess log of the CAN. Thus, I would like to know what is `src` and `address`? And what is the encoding used for the `data` field?

**Comment by adhintz** [comment]
src is the id of the CAN bus where the Panda received the message. If the Panda sent the message, the src is 128 + the CAN bus id.

address is the message identifier. This describes that type of message it is.

I think the data field in your table is in python3 byte literal syntax: https://peps.python.org/pep-3112/
