### ISSUE TITLE
How is the Pose calculated ?

### ISSUE THREAD

**Issue by kartk** [commaai/comma2k19#2]
Hey, First of all Thank You  for this Dataset.

I read through the arxiv paper and it mentions that pose is calculated by Mesh3D and was wondering if it open source or is there a paper out there explaining the same

**Comment by HaraldSchafer** [comment]
Unfortunately we did not publish a paper or open source this method. Not sure if we ever will. We essentially implemented :
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.437.1085&rep=rep1&type=pdf

**Comment by Capchenxi** [comment]
> Unfortunately we did not publish a paper or open source this method. Not sure if we ever will. We essentially implemented : http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.437.1085&rep=rep1&type=pdf

Is there any way to access the file listed above? The link is expired.
