### ISSUE TITLE
error when testing raw_read.py

### ISSUE THREAD

**Issue by zhouhao0605** [commaai/comma2k19#6]
Hi, I was trying to execute raw_reader.py to read the rlog files of my own, and I encountered the following error. 
`subprocess.CalledProcessError: Command '['make', 'PHONELIBS=/home/hao/Documents/openpilot/phonelibs']' returned non-zero exit status 2.
`
I found the error comes from the **index_log** function in **logreader.py**
`def index_log(fn):
  index_log_dir = os.path.join(os.path.dirname(os.path.realpath(__file__)), "index_log")
  index_log = os.path.join(index_log_dir, "index_log")
  phonelibs_dir = os.path.join(OP_PATH, 'phonelibs') 
  subprocess.check_call(["make", "PHONELIBS=" + phonelibs_dir], cwd=index_log_dir, stdout=subprocess.DEVNULL)
`

Acutally I can't understand what does the command ' make PHONELIBS= phonelibs_dir ' do? But the issues is coming from this command. 

I'm using python 3.6 in Ubuntu. Can anyone provide some insights?

**Comment by ducmanhnguyen** [comment]
Hi,
Did you solve the problem? Could you please show us how to solve it if it's possible. Thank you so much!

**Comment by jdacoello** [comment]
@HaoZhouGT How did you solve the issue, because I am getting the same error! Thanks
