### ISSUE TITLE
How is the data in processed_log calculated?

### ISSUE THREAD

**Issue by w9z5ebczf8n** [commaai/comma2k19#7]
Hi and thank you very much for providing this dataset!

may I ask you to provide more information about the generation of the data inside the `processed_log` directories? I assume it is generated from the `raw_log.bz2` file also provided in each segment. I had a look at the openpilot-tools, but I couldn't locate scripts required to generate all these files.

Therefore, I would like to ask you, to add your scripts that were used to generate the `processed_log` directory to this repo or at least provide some more information about its generation. I especially struggle with the `can/raw_can/t` file, as the capnp log only provides the monotonic bus time.

Thanks a lot in advance.

**Comment by HaraldSchafer** [comment]
The controlsd thread in openpilot generates and sends these messages.

https://github.com/commaai/openpilot/blob/master/selfdrive/controls/controlsd.py
